Get Player Skin
Camotoy/GeyserSkinManager pull request #8
Opened 2021-02-07 03:23 UTC by Leialoha

Using RetrieveSkin(Player) will give the latest Pocket Edition Skin, if player has a skin it returns their skin instead (Java Players).

2021-02-07 03:26 UTC, Camotoy requested changes

2021-02-07 03:26 UTC, Camotoy commented on spigot/src/main/java/com/github/camotoy/geyserskinmanager/spigot/listener/SpigotPlatformEventListener.java
> +        PlayerProfile playerProfile = player.getPlayerProfile();
This cannot be here - it's a Paper-only property, and thus will fail on Spigot. Look at my `MinecraftProfileWrapper` class for an idea of how to work around this.

2021-02-07 03:26 UTC, Camotoy commented on spigot/src/main/java/com/github/camotoy/geyserskinmanager/spigot/listener/SpigotPlatformEventListener.java
> +    public String[] RetrieveSkin(Player player) {
`retrieveSkin` is the correct formatting.

2021-02-07 03:26 UTC, Camotoy commented on spigot/src/main/java/com/github/camotoy/geyserskinmanager/spigot/listener/SpigotPlatformEventListener.java
> +        String value = "ewogICJ0aW1lc3RhbXAiIDogMTYxMjY0NzA0MzEwOCwKICAicHJvZmlsZUlkIiA6ICJmYmYyMmIyMjNjN2E0NzA0OGYwM2U0MzVhZGFhNGVhZiIsCiAgInByb2ZpbGVOYW1lIiA6ICJCZWFyZGVkU3RldmUiLAogICJzaWduYXR1cmV
I think a cleaner implementation would just be to return null and let the plugin deal with it.

2021-02-07 03:36 UTC, Leialoha commented
Updated to only get skin data that was saved, otherwise returned with null.

2021-08-03 01:46 UTC, Camotoy commented
At this point I'm going to close this since I don't think GeyserSkinManager should be used as API; use Floodgate at this point. Thank you anyway!

2021-08-03 01:46 UTC, closed without merging